# Cyber Range Team Capstone Project Summary - Red Team


## 
[![SPRINT 1 - RED TEAM ](https://drive.google.com/uc?export=view&id=1mYjdREqJPkrotr126PjU9ByedOIkYiAS)] 


There is an average of 2,200 cyberattacks per day with the United States remaining the most highly targeted country with 46% of global cyber incidences, according to research updated in January 2023 by CompTIA (CompTIA, 2023). Cybersecurity has developed to be one of the most in-demand industries in response to the growing threats. Organizations need proper security assessments to ensure that they are operating in compliance and are effective at defending the organization from unknown or “zero-day threats”. Red teaming is a proactive approach to cybersecurity that simulates real-world attacks to identify vulnerabilities and improve defenses.

In a move towards launching a full-scale cloud native cybersecurity training range environment in AWS, we are implementing several offensive security measures that consider social engineering, password cracking, network scanning, web application testing, and, exploitation, and penetration testing.
Social engineering is cyberattacks where attackers trick people into divulging sensitive information or performing actions they wouldn't normally do. The success of a social engineering attack depends on the attacker's ability to manipulate the victim's trust and emotions and can have serious consequences such as data breaches, identity theft, and financial loss. We are deploying Social-Engineer Toolkit (SET), an open-source tool that provides a range of social engineering attacks, including phishing, spear-phishing, and credential harvesting, to provide real-life scenarios of how attackers operate so clients and organizations can identify behaviors to look out for to mitigate risks.

Password cracking tools are software applications designed to reveal or recover passwords for digital authentication mechanisms. These tools use various techniques, such as brute force, dictionary attack, and hybrid attack, to guess or crack passwords. John the Ripper is a popular password-cracking tool that can crack passwords from various operating systems, including Linux, macOS, and Windows (J. the Ripper, n.d.). This tool can also use different hashing algorithms, including MD5, SHA-1, and bcrypt. To use John the Ripper, the program needs to be provided with a password file, which contains hashed passwords. A hashed password is a one-way cryptographic function that transforms a password into a fixed-length string of characters representing the original password. The program then uses the selected cracking method to try and crack the passwords. John the Ripper can also use wordlists and rulesets to modify dictionary words and increase the likelihood of cracking passwords.
